modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="dcmexpansion"
version="${file.jarVersion}"
displayName="DCM Expansion"
logoFile="dcmexpansion.png"
credits="DCM-Modpack, Kzeroko"
authors="Kzeroko"
description='''
Mod that adds contents to DCM modpack.
'''

[[dependencies.dcmexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.7a,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="hordes"
    mandatory=true
    versionRange="[1.1.5e,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="firstaid"
    mandatory=true
    versionRange="[1.11.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.9.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="tacz"
    mandatory=true
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="securitycraft"
    mandatory=true
    versionRange="[1.9.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="bettercombat"
    mandatory=true
    versionRange="[1.6.2+1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="immersive_aircraft"
    mandatory=false
    versionRange="[0.5.2+1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="pneumaticcraft"
    mandatory=false
    versionRange="[1.18.2-3.6.1-29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="coroutil"
    mandatory=false
    versionRange="[1.3.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="weather2"
    mandatory=false
    versionRange="[1.18.2-2.7.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="cold_sweat"
    mandatory=false
    versionRange="[2.2.5.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dcmexpansion]]
    modId="thirst"
    mandatory=false
    versionRange="[1.3.5,)"
    ordering="NONE"
    side="BOTH"